### PR TITLE
Add missing kernels, rename FfmpegBicubic

### PR DESCRIPTION
**Pull request by LightArrowsEXE**
Adding missing kernels we uncovered some time ago, as well as renaming FfmpegBicubic.

### CODE REVIEW

**Comment by Setsugennoao** [comment]
Ripbozo i can't complain for ffmpeg since it's not even on a minor version

**Comment by Setsugennoao** [comment]
AdobeBicubicSharper/AdobeBicubicSmoother make no sense since blur isn't implemented in resize.

Should first implement custom kernels.

**Comment by LightArrowsEXE** [comment]
> AdobeBicubicSharper/AdobeBicubicSmoother make no sense since blur isn't implemented in resize.
> 
> Should first implement custom kernels.

Can we at least accept the other change then? FfmpegBicubic stinx :(

**Comment by Setsugennoao** [comment]
Why? Where else is swscale popularily used if not ffmpeg

**Comment by LightArrowsEXE** [comment]
The name implies that it's a default used everywhere in ffmpeg, whereas from my understanding it's just the Swscale default, not a global one.

**Pull request closed without merging**
